### ISSUE TITLE
How to download the predicted data?

### ISSUE THREAD

**Issue by HelloWorldLTY** [Genentech/decima#1]
Hi, thanks for your great work. I notice that the released notebook contains information about prediction h5ad file. May I know how to download it? Thanks.

**Comment by avantikalal** [comment]
Hi, could you please clarify which notebook and which file exactly?

**Comment by avantikalal** [comment]
It is supplementary file 1 here: https://zenodo.org/records/13910842

**Comment by HelloWorldLTY** [comment]
Thanks a lot!
